### ISSUE TITLE
Staging dashboard shows empty screen

### ISSUE THREAD

**Issue by vorboyvo** [fedihost-co/platform-issues#2]
Attempting to access dashboard for services to set up a newly provisioned (test) instance. Both upon login, and also upon instance creation, I see this screen:
![image](https://github.com/fedihost-co/platform-issues/assets/27565096/fc8f02b0-3b25-4ca9-a3d1-861a4b544f36)

On Firefox 126.0.1 x86_64 on Linux (NixOS)

**Comment by S0yKaf** [comment]
Should work now, apologies.
