### ISSUE TITLE
Customer ID format - might be better if it's just numeric?

### ISSUE THREAD

**Issue by vorboyvo** [fedihost-co/platform-issues#4]
Hi, not sure if this is a problem at all but pointing it out just in case.

If the customer ID will be used for support of any kind, it's probably best that it's a number. On Staging, mine is cus_QE4UkZeM9XE3uO, which is hard to read out loud, and error-prone when transcribing it whether by hand or on a computer. If it's a number, it'll be easier to keep track of.

**Comment by S0yKaf** [comment]
These are generated by stripe so nothing we can do about it. There are easier things we can use to identify someone if we need to. either their name or their email address.
