### ISSUE TITLE
PeerTube - Cannot create archive

### ISSUE THREAD

**Issue by fatherpat64** [fedihost-co/platform-issues#5]
Hello, 

I am trying to create an archive of my content, including videos, from video.boxingpreacher.me. But the archive always fails. I don't know why. Can you help?

**Comment by S0yKaf** [comment]
Hello, 
Are you having an issue inside the peertube app or with the "export" feature on the Fedihost website?

![2024-10-14-105134_1301x416_scrot](https://github.com/user-attachments/assets/af6c757a-105f-4dbb-b986-a09283640b29)

**Comment by fatherpat64** [comment]
This is actually the export feature in the peertube app.

**Comment by S0yKaf** [comment]
Okay, thank you, I'm able to reproduce the issue. A fix is on the way. Will let you know when the issue is resolved! 

Appreciate you bringing this up to our attention.

**Comment by S0yKaf** [comment]
@fatherpat64 Exports should be working now.

**Comment by S0yKaf** [comment]
Will be assuming this is fixed. Please don't hesitate to re-open this issue if its not the case. 

Thank you!
